from fastapi import FastAPI
from  pydantic import BaseModel
from src.orchestrator.crew_manager import IncidentOrchestrator


app = FastAPI(title="Smart city incident API")
orchestrator=IncidentOrchestrator()

class IncidentRequest(BaseModel):
    description:str

@app.post("/api/v1/report-incident")
async def report_incident(request: IncidentOrchestrator):
    """
    Returns TWO objects:
    1. 'final_action_plan' (The result generated by CrewAI)
    2. 'data_context' (The raw Tensor data where the AI derived its context)
    """
    response=orchestrator.process_incident(request.description)
    return response